import { CONFIG } from "./config.js";

function deg(degrees) {
  return (degrees * Math.PI) / 180;
}

function satelliteSpec(spec) {
  return {
    ...spec,
    rotation: spec.rotation || 0,
    motionMode: spec.motionMode || "orbit",
  };
}

export const LEVELS = [
  {
    id: "tutorial-orbit",
    name: "Level 1: Tutorial Orbit",
    objective: "Large satellites are chain fuel. Small ones are cleanup shots.",
    rocketBudget: 4,
    previewHorizon: 16,
    wells: [
      {
        id: "earth",
        x: CONFIG.width * 0.58,
        y: CONFIG.height * 0.48,
        radius: 76,
        mu: 235000,
        core: "#1d3d5d",
        glow: "#4c7ba8",
        ring: "rgba(121, 224, 255, 0.26)",
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "earth", orbitFamily: "inner", debrisYield: 5, rx: 156, ry: 148, phase: -1.15, rotation: deg(8), angularSpeed: 0.2, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "transfer", debrisYield: 3, rx: 182, ry: 166, phase: -0.38, rotation: deg(62), angularSpeed: 0.17, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "relay", debrisYield: 2, rx: 220, ry: 154, phase: 0.62, rotation: deg(118), angularSpeed: 0.14, direction: -1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "sweep", debrisYield: 1, rx: 262, ry: 136, phase: 1.78, rotation: deg(164), angularSpeed: 0.12, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "outer", debrisYield: 0, rx: 308, ry: 122, phase: 2.52, rotation: deg(46), angularSpeed: 0.1, direction: -1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "polar", debrisYield: 2, rx: 212, ry: 162, phase: -2.36, rotation: deg(98), angularSpeed: 0.11, direction: 1 }),
    ],
  },
  {
    id: "tight-window",
    name: "Level 2: Tight Window",
    objective: "Hit the medium and heavy sats when they cross the shared hub.",
    rocketBudget: 3,
    previewHorizon: 17,
    wells: [
      {
        id: "earth",
        x: CONFIG.width * 0.59,
        y: CONFIG.height * 0.5,
        radius: 82,
        mu: 250000,
        core: "#163754",
        glow: "#4f88b5",
        ring: "rgba(121, 224, 255, 0.24)",
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "earth", orbitFamily: "inner", debrisYield: 5, rx: 150, ry: 144, phase: -1.46, rotation: deg(12), angularSpeed: 0.23, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "transfer", debrisYield: 3, rx: 184, ry: 164, phase: -0.52, rotation: deg(58), angularSpeed: 0.18, direction: -1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "relay", debrisYield: 2, rx: 234, ry: 150, phase: 0.68, rotation: deg(104), angularSpeed: 0.15, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "sweep", debrisYield: 1, rx: 286, ry: 134, phase: 1.64, rotation: deg(152), angularSpeed: 0.12, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "outer", debrisYield: 0, rx: 336, ry: 114, phase: 2.38, rotation: deg(34), angularSpeed: 0.09, direction: -1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "polar", debrisYield: 3, rx: 206, ry: 156, phase: -2.26, rotation: deg(88), angularSpeed: 0.14, direction: -1 }),
    ],
  },
  {
    id: "cascade-budget",
    name: "Level 3: Cascade Budget",
    objective: "Spend rockets only on the heaviest chain-makers in the inner lanes.",
    rocketBudget: 2,
    previewHorizon: 18,
    wells: [
      {
        id: "earth",
        x: CONFIG.width * 0.56,
        y: CONFIG.height * 0.52,
        radius: 88,
        mu: 265000,
        core: "#112e48",
        glow: "#406d93",
        ring: "rgba(121, 224, 255, 0.22)",
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "earth", orbitFamily: "inner", debrisYield: 5, rx: 148, ry: 142, phase: -1.12, rotation: deg(14), angularSpeed: 0.22, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "transfer", debrisYield: 3, rx: 176, ry: 160, phase: -0.18, rotation: deg(52), angularSpeed: 0.18, direction: -1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "relay", debrisYield: 2, rx: 224, ry: 148, phase: 0.86, rotation: deg(96), angularSpeed: 0.14, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "sweep", debrisYield: 1, rx: 276, ry: 130, phase: 1.84, rotation: deg(142), angularSpeed: 0.11, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "outer", debrisYield: 0, rx: 330, ry: 112, phase: 2.46, rotation: deg(26), angularSpeed: 0.09, direction: -1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "polar", debrisYield: 2, rx: 214, ry: 150, phase: -2.34, rotation: deg(82), angularSpeed: 0.12, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "transfer", debrisYield: 3, rx: 242, ry: 144, phase: 2.96, rotation: deg(120), angularSpeed: 0.1, direction: -1 }),
    ],
  },
  {
    id: "moon-crossing",
    name: "Level 4: Moon Crossing",
    objective: "Use Earth lanes to seed debris, but you should still have a clean shot at either body.",
    rocketBudget: 3,
    previewHorizon: 20,
    wells: [
      {
        id: "earth",
        x: CONFIG.width * 0.44,
        y: CONFIG.height * 0.36,
        radius: 92,
        mu: 270000,
        core: "#163754",
        glow: "#4f88b5",
        ring: "rgba(121, 224, 255, 0.24)",
      },
      {
        id: "moon",
        x: CONFIG.width * 0.78,
        y: CONFIG.height * 0.66,
        radius: 44,
        mu: 54000,
        core: "#4d5563",
        glow: "#959fb0",
        ring: "rgba(255, 209, 102, 0.22)",
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "earth", orbitFamily: "inner", debrisYield: 5, rx: 166, ry: 156, phase: -1.26, rotation: deg(10), angularSpeed: 0.19, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "transfer", debrisYield: 3, rx: 212, ry: 170, phase: -0.48, rotation: deg(62), angularSpeed: 0.15, direction: -1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "relay", debrisYield: 2, rx: 286, ry: 148, phase: 2.28, rotation: deg(120), angularSpeed: 0.11, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "sweep", debrisYield: 1, rx: 244, ry: 124, phase: 1.66, rotation: deg(88), angularSpeed: 0.14, direction: -1 }),
      satelliteSpec({ wellId: "moon", orbitFamily: "lunar", debrisYield: 3, rx: 90, ry: 82, phase: -0.38, rotation: deg(28), angularSpeed: 0.32, direction: 1 }),
      satelliteSpec({ wellId: "moon", orbitFamily: "lunarRelay", debrisYield: 1, rx: 132, ry: 74, phase: 1.72, rotation: deg(112), angularSpeed: 0.24, direction: -1 }),
    ],
  },
  {
    id: "binary-trap",
    name: "Level 5: Binary Trap",
    objective: "Read two hubs at once. Big sats on inner lanes power the whole puzzle.",
    rocketBudget: 3,
    previewHorizon: 20,
    wells: [
      {
        id: "earth",
        x: CONFIG.width * 0.42,
        y: CONFIG.height * 0.58,
        radius: 88,
        mu: 248000,
        core: "#14344f",
        glow: "#507da5",
        ring: "rgba(121, 224, 255, 0.2)",
      },
      {
        id: "moon",
        x: CONFIG.width * 0.74,
        y: CONFIG.height * 0.37,
        radius: 54,
        mu: 76000,
        core: "#5d6775",
        glow: "#b0bac7",
        ring: "rgba(255, 209, 102, 0.2)",
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "earth", orbitFamily: "inner", debrisYield: 5, rx: 146, ry: 140, phase: -1.18, rotation: deg(12), angularSpeed: 0.22, direction: 1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "transfer", debrisYield: 3, rx: 192, ry: 164, phase: -0.36, rotation: deg(56), angularSpeed: 0.17, direction: -1 }),
      satelliteSpec({ wellId: "earth", orbitFamily: "relay", debrisYield: 2, rx: 258, ry: 146, phase: 2.56, rotation: deg(116), angularSpeed: 0.12, direction: 1 }),
      satelliteSpec({ wellId: "moon", orbitFamily: "lunar", debrisYield: 3, rx: 94, ry: 86, phase: 0.82, rotation: deg(18), angularSpeed: 0.28, direction: 1 }),
      satelliteSpec({ wellId: "moon", orbitFamily: "lunarRelay", debrisYield: 1, rx: 146, ry: 82, phase: -2.2, rotation: deg(78), angularSpeed: 0.2, direction: -1 }),
      satelliteSpec({ wellId: "moon", orbitFamily: "lunarOuter", debrisYield: 0, rx: 188, ry: 66, phase: 2.9, rotation: deg(136), angularSpeed: 0.14, direction: 1 }),
    ],
  },
  {
    id: "dual-planet-lattice",
    name: "Level 6: Dual Planet Lattice",
    objective: "Two planets, two local lanes, plus shared-field satellites that loop around both bodies.",
    rocketBudget: 2,
    previewHorizon: 22,
    wells: [
      {
        kind: "planet",
        id: "tide",
        x: CONFIG.width * 0.34,
        y: CONFIG.height * 0.58,
        radius: 86,
        mu: 238000,
        core: "#17334d",
        glow: "#5885b0",
        ring: "rgba(121, 224, 255, 0.22)",
      },
      {
        kind: "planet",
        id: "forge",
        x: CONFIG.width * 0.72,
        y: CONFIG.height * 0.34,
        radius: 80,
        mu: 225000,
        core: "#40253d",
        glow: "#a66e92",
        ring: "rgba(255, 143, 171, 0.2)",
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "tide", orbitFamily: "inner", debrisYield: 5, rx: 152, ry: 144, phase: -1.22, rotation: deg(18), angularSpeed: 0.2, direction: 1 }),
      satelliteSpec({ wellId: "tide", orbitFamily: "transfer", debrisYield: 3, rx: 214, ry: 162, phase: -0.42, rotation: deg(54), angularSpeed: 0.15, direction: -1 }),
      satelliteSpec({ motionMode: "ballistic", orbitFamily: "relay", debrisYield: 2, x: CONFIG.width * 0.507, y: CONFIG.height * 0.525, vx: -33, vy: -24 }),
      satelliteSpec({ motionMode: "ballistic", orbitFamily: "sweep", debrisYield: 2, x: CONFIG.width * 0.42, y: CONFIG.height * 0.245, vx: 30, vy: 13 }),
      satelliteSpec({ wellId: "forge", orbitFamily: "sweep", debrisYield: 1, rx: 190, ry: 146, phase: 1.4, rotation: deg(78), angularSpeed: 0.16, direction: -1 }),
      satelliteSpec({ wellId: "forge", orbitFamily: "outer", debrisYield: 5, rx: 250, ry: 150, phase: 2.62, rotation: deg(138), angularSpeed: 0.11, direction: 1 }),
      satelliteSpec({ wellId: "forge", orbitFamily: "polar", debrisYield: 0, rx: 296, ry: 120, phase: -2.18, rotation: deg(170), angularSpeed: 0.09, direction: -1 }),
    ],
  },
  {
    id: "shepherd-moon",
    name: "Level 7: Shepherd Moon",
    objective: "Seed debris from the planet first. The moon is a collector, not the opening shot.",
    rocketBudget: 2,
    previewHorizon: 23,
    wells: [
      {
        kind: "planet",
        id: "giant",
        x: CONFIG.width * 0.48,
        y: CONFIG.height * 0.56,
        radius: 96,
        mu: 286000,
        core: "#18354f",
        glow: "#5f90ba",
        ring: "rgba(121, 224, 255, 0.24)",
      },
      {
        kind: "planet",
        id: "shepherd",
        x: CONFIG.width * 0.8,
        y: CONFIG.height * 0.28,
        radius: 46,
        mu: 62000,
        core: "#636975",
        glow: "#b7c1cc",
        ring: "rgba(255, 233, 168, 0.22)",
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "giant", orbitFamily: "inner", debrisYield: 5, rx: 164, ry: 152, phase: -1.32, rotation: deg(8), angularSpeed: 0.19, direction: 1 }),
      satelliteSpec({ wellId: "giant", orbitFamily: "transfer", debrisYield: 3, rx: 210, ry: 172, phase: -0.3, rotation: deg(52), angularSpeed: 0.15, direction: -1 }),
      satelliteSpec({ wellId: "giant", orbitFamily: "relay", debrisYield: 2, rx: 286, ry: 150, phase: 2.44, rotation: deg(122), angularSpeed: 0.11, direction: 1 }),
      satelliteSpec({ wellId: "giant", orbitFamily: "sweep", debrisYield: 0, rx: 244, ry: 122, phase: 1.66, rotation: deg(90), angularSpeed: 0.13, direction: -1 }),
      satelliteSpec({ wellId: "shepherd", orbitFamily: "lunar", debrisYield: 1, rx: 82, ry: 76, phase: 0.44, rotation: deg(16), angularSpeed: 0.31, direction: 1 }),
      satelliteSpec({ wellId: "shepherd", orbitFamily: "lunarRelay", debrisYield: 3, rx: 128, ry: 72, phase: -2.12, rotation: deg(86), angularSpeed: 0.22, direction: -1 }),
      satelliteSpec({ wellId: "shepherd", orbitFamily: "lunarOuter", debrisYield: 0, rx: 170, ry: 60, phase: 2.82, rotation: deg(132), angularSpeed: 0.16, direction: 1 }),
    ],
  },
  {
    id: "triple-body-weave",
    name: "Level 16: Triple-Body Weave",
    objective: "Three wells share the same space. Read which local hit actually threads debris through the whole weave.",
    rocketBudget: 2,
    previewHorizon: 30,
    wells: [
      {
        kind: "planet",
        id: "anchor",
        x: CONFIG.width * 0.34,
        y: CONFIG.height * 0.58,
        radius: 86,
        mu: 236000,
        core: "#17334d",
        glow: "#5884ae",
        ring: "rgba(121, 224, 255, 0.22)",
      },
      {
        kind: "planet",
        id: "flare",
        x: CONFIG.width * 0.7,
        y: CONFIG.height * 0.36,
        radius: 76,
        mu: 210000,
        core: "#44273f",
        glow: "#b27699",
        ring: "rgba(255, 143, 171, 0.2)",
      },
      {
        kind: "planet",
        id: "pebble",
        x: CONFIG.width * 0.6,
        y: CONFIG.height * 0.7,
        radius: 38,
        mu: 48000,
        core: "#6d7567",
        glow: "#c7d0c1",
        ring: "rgba(196, 255, 173, 0.18)",
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "anchor", orbitFamily: "inner", debrisYield: 5, rx: 150, ry: 144, phase: -1.24, rotation: deg(18), angularSpeed: 0.194, direction: 1 }),
      satelliteSpec({ wellId: "anchor", orbitFamily: "transfer", debrisYield: 3, rx: 216, ry: 164, phase: -0.46, rotation: deg(56), angularSpeed: 0.146, direction: -1 }),
      satelliteSpec({ motionMode: "ballistic", orbitFamily: "relay", debrisYield: 2, x: CONFIG.width * 0.51, y: CONFIG.height * 0.48, vx: -18, vy: 28 }),
      satelliteSpec({ wellId: "flare", orbitFamily: "outer", debrisYield: 5, rx: 236, ry: 146, phase: 2.52, rotation: deg(138), angularSpeed: 0.108, direction: 1 }),
      satelliteSpec({ wellId: "flare", orbitFamily: "sweep", debrisYield: 1, rx: 182, ry: 142, phase: 1.34, rotation: deg(80), angularSpeed: 0.154, direction: -1 }),
      satelliteSpec({ wellId: "pebble", orbitFamily: "lunarRelay", debrisYield: 3, rx: 104, ry: 70, phase: -2.1, rotation: deg(94), angularSpeed: 0.246, direction: -1 }),
      satelliteSpec({ wellId: "pebble", orbitFamily: "lunar", debrisYield: 1, rx: 72, ry: 64, phase: 0.68, rotation: deg(20), angularSpeed: 0.33, direction: 1 }),
    ],
  },
  {
    id: "final-convergence",
    name: "Level 17: Final Convergence",
    objective: "Everything matters now: timing, stream direction, relays, and gravity routing. Clear the sector with only two rockets.",
    rocketBudget: 2,
    previewHorizon: 32,
    wells: [
      {
        kind: "planet",
        id: "anchor",
        x: CONFIG.width * 0.36,
        y: CONFIG.height * 0.57,
        radius: 88,
        mu: 244000,
        core: "#17354f",
        glow: "#5a89b4",
        ring: "rgba(121, 224, 255, 0.22)",
      },
      {
        kind: "planet",
        id: "flare",
        x: CONFIG.width * 0.72,
        y: CONFIG.height * 0.33,
        radius: 82,
        mu: 228000,
        core: "#43263e",
        glow: "#aa7297",
        ring: "rgba(255, 143, 171, 0.2)",
      },
      {
        kind: "composite",
        id: "shard",
        x: CONFIG.width * 0.58,
        y: CONFIG.height * 0.68,
        visualRadius: 78,
        core: "#5b5247",
        glow: "#b9a28a",
        ring: "rgba(242, 208, 169, 0.16)",
        lobes: [
          { id: "north", x: -20, y: -12, radius: 28, mu: 32000 },
          { id: "east", x: 18, y: 6, radius: 34, mu: 42000 },
          { id: "south", x: -6, y: 28, radius: 24, mu: 26000 },
        ],
      },
    ],
    satellites: [
      satelliteSpec({ wellId: "anchor", orbitFamily: "inner", debrisYield: 5, rx: 152, ry: 146, phase: -1.26, rotation: deg(18), angularSpeed: 0.19, direction: 1 }),
      satelliteSpec({ wellId: "anchor", orbitFamily: "transfer", debrisYield: 3, rx: 214, ry: 166, phase: -0.4, rotation: deg(58), angularSpeed: 0.146, direction: -1 }),
      satelliteSpec({ motionMode: "ballistic", orbitFamily: "relay", debrisYield: 2, x: CONFIG.width * 0.52, y: CONFIG.height * 0.5, vx: -24, vy: 24 }),
      satelliteSpec({ motionMode: "ballistic", orbitFamily: "sweep", debrisYield: 2, x: CONFIG.width * 0.66, y: CONFIG.height * 0.7, vx: 16, vy: -10 }),
      satelliteSpec({ wellId: "flare", orbitFamily: "outer", debrisYield: 5, rx: 244, ry: 150, phase: 2.58, rotation: deg(142), angularSpeed: 0.108, direction: 1 }),
      satelliteSpec({ wellId: "flare", orbitFamily: "sweep", debrisYield: 1, rx: 186, ry: 144, phase: 1.44, rotation: deg(84), angularSpeed: 0.154, direction: -1 }),
      satelliteSpec({ motionMode: "ballistic", orbitFamily: "asteroidSkim", debrisYield: 3, x: CONFIG.width * 0.58 + 98, y: CONFIG.height * 0.68 - 24, vx: 10, vy: 18 }),
      satelliteSpec({ motionMode: "ballistic", orbitFamily: "asteroidOuter", debrisYield: 0, x: CONFIG.width * 0.58 - 132, y: CONFIG.height * 0.68 + 10, vx: -6, vy: -16 }),
    ],
  },
];
